// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCouCfPC8fdv3mqvrI-eUPFteuC-lXzZTA',
    appId: '1:57540737332:web:a7da8331c2a5768c298d61',
    messagingSenderId: '57540737332',
    projectId: 'zimkey-admin-panel',
    authDomain: 'zimkey-admin-panel.firebaseapp.com',
    storageBucket: 'zimkey-admin-panel.appspot.com',
    measurementId: 'G-CXP1GRQGYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzQIIDEtr97LaL7uDHJKt1IJGHAO6rWiU',
    appId: '1:57540737332:android:a2b8d7ee63250206298d61',
    messagingSenderId: '57540737332',
    projectId: 'zimkey-admin-panel',
    storageBucket: 'zimkey-admin-panel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtof0VWdol8pdUpvtE1dL1nItmputrhAU',
    appId: '1:57540737332:ios:4f321fd5ad053c67298d61',
    messagingSenderId: '57540737332',
    projectId: 'zimkey-admin-panel',
    storageBucket: 'zimkey-admin-panel.appspot.com',
    iosBundleId: 'com.zimkey.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtof0VWdol8pdUpvtE1dL1nItmputrhAU',
    appId: '1:57540737332:ios:9028067503f555a2298d61',
    messagingSenderId: '57540737332',
    projectId: 'zimkey-admin-panel',
    storageBucket: 'zimkey-admin-panel.appspot.com',
    iosBundleId: 'com.zimkey.customer.RunnerTests',
  );
}
